src/EV/PlatformBundle/Entity/Application.php
<?php

namespace EV\PlatformBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Table(name="application")
 * @ORM\Entity(repositoryClass="EV\PlatformBundle\Repository\ApplicationRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Application
{
    /**
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(name="last_name", type="string", length=255)
     * @Assert\Length(min="2", max="255")
     * @Assert\NotBlank()
     */
    private $last_name;

    /**
     * @ORM\Column(name="first_name", type="string", length=255)
     * @Assert\Length(min="2", max="255")
     * @Assert\NotBlank()
     */
    private $first_name;

    /**
     * @ORM\Column(name="content", type="text")
     * @Assert\NotBlank()
     */
    private $content;

    /**
     * @ORM\Column(name="date", type="datetime")
     * @Assert\DateTime()
     * @Assert\NotBlank()
     */
    private $date;

    /**
     * @ORM\ManyToOne(targetEntity="EV\PlatformBundle\Entity\Advert", inversedBy="applications")
     * @ORM\JoinColumn(nullable=true)
     */
    private $advert;

    /**
     * @ORM\ManyToOne(targetEntity="EV\UserBundle\Entity\User", inversedBy="applications")
     * @ORM\JoinColumn(nullable=true)
     */
    private $user;

//    /**
//     * @ORM\Column(type="string")
//     * @Assert\Ip()
//     */
//    private $ip;






    /**
     * Application constructor.
     */
    public function __construct()
    {
        $this->date = new \Datetime();
    }


    /**
     * @ORM\PostPersist()
     */
    public function increase(){
        if ($this->getAdvert() !== null) {
            $this->getAdvert()->increaseApplication();
        }
    }

    /**
     * @ORM\PreRemove()
     */
    public function decrease() {
        $this->getAdvert()->decreaseApplication();
    }



    /**
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }


    /**
     * @param $last_name
     * @return $this
     */
    public function setLastName($last_name)
    {
        $this->last_name = $last_name;

        return $this;
    }

    /**
     * @return string
     */
    public function getLastName()
    {
        return $this->last_name;
    }


    /**
     * @param $first_name
     * @return $this
     */
    public function setFirstName($first_name)
    {
        $this->first_name = $first_name;

        return $this;
    }

    /**
     * @return string
     */
    public function getFirstName()
    {
        return $this->first_name;
    }


    /**
     * @param $content
     * @return $this
     */
    public function setContent($content)
    {
        $this->content = $content;

        return $this;
    }

    /**
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }


    /**
     * @param \Datetime $date
     * @return $this
     */
    public function setDate(\Datetime $date)
    {
        $this->date = $date;

        return $this;
    }

    /**
     * @return \Datetime
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * @param mixed $advert
     */
    public function setAdvert($advert)
    {
        $this->advert = $advert;
    }

    /**
     * @return mixed
     */
    public function getAdvert()
    {
        return $this->advert;
    }


    /**
     * @return mixed
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @param mixed $user
     */
    public function setUser($user)
    {
        $this->user = $user;
    }

//    /**
//     * @return mixed
//     */
//    public function getIp()
//    {
//        return $this->ip;
//    }
//
//    /**
//     * @param mixed $ip
//     */
//    public function setIp($ip)
//    {
//        $this->ip = $ip;
//    }

}

src/EV/PlatformBundle/Resources/views/dashboardPlatform.html.twig
{% extends "EVPlatformBundle::layout.html.twig" %}


{% block title %} {{ parent() }} (accueil) {% endblock title %}

{% block subtitle %}<h1>Tableau de bord</h1>{% endblock subtitle %}


{% block evplatform_body %}
    <div>
        {% if is_granted('ROLE_COMPANY') %}
            <div class="row">
                <div class="col">
                    <h3 class="padding-top-3">Mes dernières annonces postées</h3>
                </div>
                <div class="col-1">
                    <p class="text-right">
                        <a class="btn btn-info" href="{{ path('ev_platform_list_all_adverts') }}">Voir tout</a>
                    </p>
                </div>
            </div>
            {{ render(controller("EVPlatformBundle:Dashboard:myLastsAdverts", {'limit':3})) }}
        </div>


        <div>
            <div class="row">
                <div class="col">
                    <h3 class="padding-top-3">Dernières candidatures reçues</h3>
                </div>
                <div class="col-1">
                    <p class="text-right">
                        <a class="btn btn-info" href="{{ path('ev_platform_list_all_applications') }}">Voir tout</a>
                    </p>
                </div>
            </div>
            {{ render(controller("EVPlatformBundle:Dashboard:myLastsApplications", {'limit':3})) }}
        {% elseif is_granted("ROLE_CANDIDATE") %}
            <div class="row">
                <div class="col">
                    <h3 class="padding-top-3">Les dernières annonces postées</h3>
                </div>
                <div class="col-1">
                    <p class="text-right">
                        <a class="btn btn-info" href="{{ path('ev_platform_list_all_adverts') }}">Voir tout</a>
                    </p>
                </div>
            </div>
            {% if listAdverts > 0 %}
                <ul>
                    {% for advert in listAdverts %}
                        <li>
                            <a href="{{ path('ev_platform_view_advert', {'id': advert.id}) }}">
                                {{ advert.title }}
                            </a>
                            par {{ advert.user.username }},
                            le {{ advert.date|date('d/m/Y') }}
                        </li>
                    {% endfor %}
                </ul>

            {% else %}
                <div role="alert">
                    Aucune annonce n'a encore été postée.
                </div>
            {% endif %}
            </div>


            <div>
                <div class="row">
                    <div class="col">
                        <h3 class="padding-top-3">Mes dernières candidatures envoyées</h3>
                    </div>
                    <div class="col-1">
                        <p class="text-right">
                            <a class="btn btn-info" href="{{ path('ev_platform_list_all_applications') }}">Voir tout</a>
                        </p>
                    </div>
                </div>
                {% if listApplications|length > 0 %}
                    <ul>
                        {% for application in listApplications %}
                            <li>
                                <a href="{{ path ('ev_platform_readApplication', {'idadvert': application.advert.id, 'id': application.id}) }}">
                                    Candidature n°CA{{ application.advert.id }}{{ application.id }}
                                </a>
                                par <strong>{{ application.firstName }} {{ application.lastName | upper }}</strong>
                                pour "<i>{{ application.advert.title }}</i>",
                                le {{ application.date | date ('d-m-Y') }} à {{ application.date | date ('H:i') }}
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <div role="alert">
                        Vous n'avez encore reçu aucune annonce.
                    </div>
                {% endif %}
        {% endif %}
    </div>
{% endblock %}

src/EV/PlatformBundle/Resources/views/layout.html.twig
{% extends "EVCoreBundle::layout.html.twig" %}

{% block title %}{{ parent() }} - Annonces{% endblock %}

{#{% block stylesheets %}#}
    {#<link rel="stylesheet" href="{{ asset('bootstrap-4.0.0-alpha.6/dist/css/bootstrap.css') }}">#}
{#{% endblock %}#}

{% block jumbotron %}
    <h1 class="display-3">Ma plateforme d'annonces</h1>
    <p class="lead">Retrouvez toute une collection d'annonces bidons !</p>
{% endblock jumbotron %}

{% block menu %}
    <h3>Accueil</h3>
    <ul class="nav flex-column">
        <li class="nav-item"><a href="{{ path('ev_platform_dashboard') }}" class="nav-link">Accueil</a></li>
        <li class="nav-item"><a href="{{ path('fos_user_profile_show') }}" class="nav-link">Mon profil</a></li>
    </ul>
    {%  if is_granted('ROLE_COMPANY') %}
        <h3>Mes annonces</h3>
        <ul class="nav flex-column">
            <li class="nav-item"><a href="{{ path('ev_platform_add_advert') }}" class="nav-link">Ajouter une annonce</a></li>
            <li class="nav-item"><a href="{{ path('ev_platform_list_all_adverts') }}" class="nav-link">Toutes mes annonces</a></li>
        </ul>
        <h3>Les candidatures</h3>
        <ul class="nav flex-column">
            <li class="nav-item"><a href="{{ path('ev_platform_list_all_applications') }}" class="nav-link">Mes candidatures reçues</a></li>
        </ul>
        {%  elseif is_granted('ROLE_CANDIDATE') %}
            <h3>Gestion</h3>
            <ul class="nav flex-column">
                <li class="nav-item"><a href="{{ path('ev_platform_list_all_adverts') }}" class="nav-link">Toutes les annonces</a></li>
                <li class="nav-item"><a href="{{ path('ev_platform_list_all_applications') }}" class="nav-link">Voir mes candidatures</a></li>
            </ul>
        {% endif %}

    {% if is_granted('ROLE_CANDIDATE') %}
        <h4>Dernières annonces</h4>
        {{ render(controller("EVPlatformBundle:Dashboard:lastsAdverts_menu", {'limit':3, 'id':0})) }}
    {% endif %}
{% endblock menu %}

{% block body %}
    {% block subtitle %}{% endblock subtitle %}

    <hr>

    {# On définit un nouveau bloc, que les vues du bundle pourront remplir #}
    {% block evplatform_body %}{% endblock evplatform_body %}
{% endblock body %}